### PR TITLE
Sort by latest and oldest

### PR DESCRIPTION
**Pull request by SebiderSushi**
Split "By installation time" into "Latest first" and "Oldest first"

I filled up the Arrays in all translations with the english values since otherwise the sort modes are not available to the user and the app might even crash.

### CODE REVIEW

**Comment by ligi** [comment]
Sorry for the *very* late reply - merged your other PRs - but not sure about the use-case of this one - why would I want to see my oldest entries first in a launcher? I see the case for last installed but not really for the oldest first.

**Comment by SebiderSushi** [comment]
bump

**Comment by SebiderSushi** [comment]
bump

**Comment by SebiderSushi** [comment]
bump

**Comment by ligi** [comment]
sorry - forgot about this one - but still do not see a use-case for oldest first.

**Comment by SebiderSushi** [comment]
Then we'll just change the sorting direction? Since this is a one character you could just do it or should I do it anyway and you merge it via pull request?

**Comment by ligi** [comment]
I will do it

**Comment by SebiderSushi** [comment]
nice :)

**Comment by SebiderSushi** [comment]
when will you do it?
(also don't forget to add the sortbypin comparator for nested sorting)

**Pull request closed without merging**
