### PR TITLE
new sorting mode and bug fix of unsorted mode

### PR DESCRIPTION
**Pull request by KennethPrentiss**
Hi! I fixed issue https://github.com/ligi/FAST/issues/73 and added new mode for sorting: "installed time", very useful for me.

### CODE REVIEW

**Comment by ligi** [comment]
I think you forgot to push some files ( e.g. AppInfoSortByLastInstalled.java )

**Comment by KennethPrentiss** [comment]
Thanks! Check it again

**Comment by ligi** [comment]
thanks, but I still see 2 issues:
../../src/main/java/org/ligi/fast/model/AppInfo.java:83: Field requires API level 9 (current min is 7): android.content.pm.PackageInfo#lastUpdateTime
  80 
  81         try{
  82 		pi=pmManager.getPackageInfo(packageName,0);
  83 	        installTime=pi.lastUpdateTime;
  84 		}catch (NameNotFoundException e){
  85 			// TODO Auto-generated catch block

and also we have to make sure that transition between versions is smooth

**Comment by KennethPrentiss** [comment]
Just change API version.
Look here: http://images.dailytech.com/nimage/Android_Version_Distribution_May_2015_Wide.png

**Comment by ligi** [comment]
I will just remove the function for them - but I like the support of old versions ;-)
have to check the update though - what happens when you migrate to the new format with the new field

**Comment by KennethPrentiss** [comment]
I'm not going to touch it at all, it works perfectly for me :)

**Comment by ligi** [comment]
That's all right - I will do it when there is time

**Pull request merged**
